import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/modules/Header";
import Navbar from "@/modules/Navbar";
import Session from "@/components/Session";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr">
      <body className={`${inter.className} text-white bg-main-dark`}>
        <div className="flex">
          <Navbar />
          <div className="w-full">
            <Header />
            <Session>{children}</Session>
          </div>
        </div>
      </body>
    </html>
  );
}
